"""empty message

Revision ID: 299b6c8717c2
Revises: 3644d2a61103
Create Date: 2017-10-07 00:26:18.812155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299b6c8717c2'
down_revision = '3644d2a61103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updatedAt')
    op.drop_column('user', 'createdAt')
    op.drop_column('post', 'createdAt')
    # ### end Alembic commands ###
